services:
    site.link.web_archive_consumer:
        class:      Application\Bundle\SiteBundle\Consumer\WebArchiveConsumer
        tags:       [{ name: sonata.notification.consumer, type: web_archive }]
        arguments:
            - '@site.link.url_manager'
