services:
    site.link.analyse_report_factory:
        class:      Application\Component\Link\Factory\AnalyseReportFactory

    site.link.robots_factory:
        class:      Application\Bundle\SiteBundle\Factory\RobotsFactory
        arguments:
            - '@site.link.robots_repository'

    site.link.url_factory:
        class:      Application\Bundle\SiteBundle\Factory\UrlFactory
        arguments:
            - '@site.link.url_manager'
