services:
    site.link.analyse_report_factory:
        class:      Application\Component\Link\Factory\AnalyseReportFactory

    site.link.host_factory:
        class:      Application\Component\Link\Factory\HostFactory

    site.link.parser_report_factory:
        class:      Application\Component\Link\Factory\ParserReportFactory

    site.link.robots_factory:
        class:      Application\Bundle\SiteBundle\Factory\RobotsFactory
        arguments:
            - '@site.link.robots_repository'

    site.link.site_factory:
        class:      Application\Component\Link\Factory\SiteFactory
        arguments:
            - '@site.link.site_repository'

    site.link.url_factory:
        class:      Application\Bundle\SiteBundle\Factory\UrlFactory
        arguments:
            - '@site.link.url_manager'
