services:
    # Fake service for sonata_notification
    doctrine:
        class:      Application\Bridge\Sonata\Notification\DoctrineRegistry
        arguments:
            - '@doctrine.odm.mongodb.document_manager'

parameters:
    user-agent-bot:       'Whatisurlbot'
    user-agent-version:   '0.1'
    user-agent-full:      '%user-agent-bot%/%user-agent-version% (+http://www.whatisurl.com/#bot)'

imports:
    - { resource: parameters.yml }

    # third party
    - { resource: vendor/doctrine_mongo.yml }
    - { resource: vendor/sonata_notification.yml }

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
